export const timeSlots = [
    "9:00 am – 12:00 pm",
    "12:00 pm – 3:00 pm", 
    "3:00 pm – 6:00 pm",
    "6:00 pm – 8:00 pm"
];

export const areas = [
    "Abu Hail",
    "Academic City",
    "Akoya Oxygen", 
    "Al Awir",
    "Al Bada'a",
    "Al Baraha",
    "Al Barari",
    "Al Barsha 1",
    "Al Barsha 2", 
    "Al Barsha 3",
    "Al Barsha South",
    "Al Dhagaya",
    "Al Furjan",
    "Al Garhoud",
    "Al Hamriya",
    "Al Hudaiba",
    "Al Jaddaf",
    "Al Jaffiliya",
    "Al Karama",
    "Al Khabaisi",
    "Al Khawaneej 1",
    "Al Khawaneej 2",
    "Al Mamzar",
    "Al Manara",
    "Al Mankhool",
    "Al Mina",
    "Al Mizhar 1",
    "Al Mizhar 2",
    "Al Muntazah",
    "Al Muraqqabat",
    "Al Murar",
    "Al Mushrif",
    "Al Muteena",
    "Al Nahda 1",
    "Al Nahda 2",
    "Al Quoz 1",
    "Al Quoz 2",
    "Al Quoz 3",
    "Al Quoz 4",
    "Al Quoz Industrial Area 1",
    "Al Quoz Industrial Area 2",
    "Al Quoz Industrial Area 3",
    "Al Quoz Industrial Area 4",
    "Al Qusais 1",
    "Al Qusais 2",
    "Al Qusais 3",
    "Al Qusais Industrial Area 1",
    "Al Qusais Industrial Area 2",
    "Al Qusais Industrial Area 3",
    "Al Qusais Industrial Area 4",
    "Al Qusais Industrial Area 5",
    "Al Raffa",
    "Al Ras",
    "Al Rashidiya",
    "Al Rigga",
    "Al Sabkha",
    "Al Safa 1",
    "Al Safa 2",
    "Al Satwa",
    "Al Shindagha",
    "Al Souq Al Kabeer",
    "Al Sufouh 1",
    "Al Sufouh 2",
    "Al Twar 1",
    "Al Twar 2",
    "Al Twar 3",
    "Al Waheda",
    "Al Warqa 1",
    "Al Warqa 2",
    "Al Warqa 3",
    "Al Warqa 4",
    "Al Warqa 5",
    "Al Wasl",
    "Arabian Ranches",
    "Arabian Ranches 2",
    "Arjan",
    "Baniyas Square",
    "Barsha Heights - TECOM",
    "Bukadra",
    "Bur Dubai",
    "Business Bay",
    "Corniche Deira",
    "Damac Hills",
    "Deira",
    "Deira Water Front",
    "DIFC",
    "Discovery Gardens",
    "Downtown Dubai",
    "Downtown Jebel Ali",
    "Dubai Airport Freezone",
    "Dubai Cargo Village",
    "Dubai Design District",
    "Dubai Falcon City",
    "Dubai Festival City",
    "Dubai Healthcare City",
    "Dubai Hills",
    "Dubai International Airport",
    "Dubai Internet City - DIC",
    "Dubai Investments Park 1",
    "Dubai Investments Park 2",
    "Dubai Lifestyle City",
    "Dubai Marina",
    "Dubai Maritime City",
    "Dubai Media City",
    "Dubai Motor City",
    "Dubai Silicon Oasis",
    "Dubai South",
    "Dubai Sports City",
    "Dubai Studio City",
    "Dubai Techno Park",
    "Dubai World Central - DWC",
    "Dubai World Trade Center - DWTC",
    "Emirates Hills",
    "Gardens",
    "Global Village",
    "Green Community",
    "Green Community Motor City",
    "Hatta",
    "Hor Al Anz",
    "Hor Al Anz East",
    "Ibn Batutta Mall",
    "IMPZ",
    "International City",
    "International City 2",
    "Jebel Ali 1",
    "Jebel Ali 2",
    "Jebel Ali Freezone",
    "Jebel Ali Freezone Extension",
    "Jebel Ali Industrial Area",
    "Jebel Ali Village",
    "Jumeirah 1",
    "Jumeirah 2",
    "Jumeirah 3",
    "Jumeirah Beach Residence - JBR",
    "Jumeirah Golf Estates",
    "Jumeirah Heights",
    "Jumeirah Islands",
    "Jumeirah Lakes Towers - JLT",
    "Jumeirah Park",
    "Jumeirah Village Circle - JVC",
    "Jumeirah Village Triangle - JVT",
    "Knowledge Village",
    "Layan Community",
    "Legends",
    "Liwan",
    "Majan",
    "Meadows",
    "Meydan South",
    "Mira Community",
    "Mirdif",
    "Mohammed Bin Rashed City",
    "Mudon",
    "Muhaisnah 1",
    "Muhaisnah 2",
    "Muhaisnah 3",
    "Muhaisnah 4",
    "Nad Al Sheba 1",
    "Nad Al Sheba 2",
    "Nad Al Sheba 3",
    "Nad Al Sheba 4",
    "Nadd Al Hamar",
    "Nadd Al Shamma",
    "Naif",
    "Oud Al Muteena",
    "Oud Metha",
    "Palm Jumeirah",
    "Port Rashid",
    "Port Saeed",
    "Ras Al Khor",
    "Ras Al Khor Indsutrial Area 1",
    "Ras Al Khor Indsutrial Area 2",
    "Ras Al Khor Indsutrial Area 3",
    "Remraam",
    "Rigga Al Buteen",
    "Springs",
    "The Greens",
    "The Lakes",
    "The Palm Deira",
    "The Palm Jebel Ali",
    "The Skycourts",
    "The Sustainable City",
    "The Villa",
    "Townsquare",
    "Um Al Sheif",
    "Umm Hurair 1",
    "Umm Hurair 2",
    "Umm Ramool",
    "Umm Suqeim 1",
    "Umm Suqeim 2",
    "Umm Suqeim 3",
    "Wadi Alamardi",
    "Warsan 1",
    "Warsan 2",
    "Waterfront",
    "Zaabeel 1",
    "Zaabeel 2"
];

export const countryPhoneCodes = [
    { code: "AE", label: "+971", flag: "ae" },
    { code: "US", label: "+1", flag: "us" },
    { code: "GB", label: "+44", flag: "gb" },
    { code: "IN", label: "+91", flag: "in" }
];
